// Global canvas variables
let canvas = null;
let context = null;

// Is called from index.html once the user has filled out ID information
// Initialises the transition from Start Screen to Game Area
function startGame() {
  console.log("test")

  // Player information is retrieved and checked
  // Then PlayerId is created and stored
  const initials = document.getElementById("initials").value.trim().toUpperCase();
  const day = document.getElementById("birthDay").value.trim()
  const month = document.getElementById("birthMonth").value.trim()

  if (!initials || !day || !month) {
    alert("Vennligst fyll ut alle felt (initialer, dag og måned).");
    return;
  }

  const playerID = `${initials}${day}${month}`;
  player.id = playerID;

  // Changes page from Start Screen to Game Area  
  document.getElementById("loginSection").style.display = "none";
  document.getElementById("app").style.display = "block";
  updateGameArea();
  initCanvas();
}


// Is called by clicking the Next Campaign button generated by updateEndScreen()
// Initialises the transition from End Screen to Game Area and the next campaign
function nextCampaign(){
  // Resets values to avoid crashes and "Ghosts"
  model.game.currentScenario = 0;
  model.currentScenario = {
    tokens: [],
    pools: [],
    lanes: [],
    nodes: [],
    connectors: []
  };

  // Sets up game area
  document.getElementById("end").style.display = "none";
  document.getElementById("app").style.display = "block";
  model.game.campaignFilepath = model.loadedScenarioData.aboutCampaign.nextCampaign
  initCanvas();
}


// Is called by startGame() and nextCampaign()
// Initialises the play area by loading in all necessary elements and drawing the canvas
async function initCanvas() 
{
  // Gets the canvas element set up by view.js - updateGameArea() and sets their properties
  canvas = document.getElementById('BPMNcanvas');
  context = canvas.getContext('2d');
  context.canvas.width = model.canvasProperties.width;
  context.canvas.height = model.canvasProperties.height + 100;
  context.fillStyle = model.canvasProperties.backgroundColor;
  context.fillRect(0, 0, model.canvasProperties.width, model.canvasProperties.height);
  console.log("Testtttt");

  // Adds mouse and key listeners for learner interaction
  canvas.addEventListener('mousedown', mouseDown);
  canvas.addEventListener('mousemove', mouseMove);
  canvas.addEventListener('mouseup', mouseUp);
  canvas.addEventListener("contextmenu", (e) => e.preventDefault());
  document.addEventListener('keydown', (e) => {if(e.key == 'Delete'){ resetConnections(); }});

  // Loads and deploys game and scenario data
  const scenarioData = await loadScenarioJSON(model.game.campaignFilepath)
  model.loadedScenarioData = scenarioData;
  loadGameData();
  loadScenarioInformation();
  loadScenarioData();
  draw();
  tutorialImage(); 
}


// Is called by initCanvas()
// Stores and displayes campaign information
function loadGameData(){
  const gameData = model.loadedScenarioData.aboutCampaign;
  model.game.numberOfScenarios = gameData.numberOfScenarios;
  model.game.moduleTitle = gameData.moduleTitle;
  model.game.moduleDescription = gameData.moduleDescription;
  model.game.endScreenText = gameData.endScreenText;
  document.getElementById('moduleTitleHeader').innerText = model.game.moduleTitle;
  document.getElementById('moduleTextHeader').innerText = model.game.moduleDescription;

  // Hide/show verification UI based on campaign setting
  const verifyBtn = document.getElementById("verifyBtn");
  const feedbackText = document.getElementById("taskVerificationText");
  
  if (gameData.hiddenResults === true) {
    verifyBtn.style.display = "none";
    feedbackText.style.display = "none";
  } else {
    verifyBtn.style.display = "inline-block";
    feedbackText.style.display = "block";
  }
}


// Is called by initCanvas() and nextScenario()
// Displayes scenario information
function loadScenarioInformation(){
  document.getElementById('taskText').innerText =
    model.loadedScenarioData.scenarios[model.game.currentScenario].scenarioTitle + "\n" +
    model.loadedScenarioData.scenarios[model.game.currentScenario].scenarioDescription
}


// Is called by initCanvas() and nextScenario()
// Loads information from loadedScenarioData into model.currentScenario and sets coordinates/sizes of elements
function loadScenarioData(){
  const scenario = model.loadedScenarioData.scenarios[model.game.currentScenario]
  model.currentScenario.pools = loadStaticElements(scenario.static?.pools || []);
  model.currentScenario.lanes = loadStaticElements(scenario.static?.lanes || []);
  model.currentScenario.tokens = scenario.tokens;

  // Handles if scenarios are building on each other or if they are reset
  if (scenario.resetCanvas) {
    model.currentScenario.nodes = []; 
    model.currentScenario.nodes = processNodes(scenario.nodes);
    model.currentScenario.failureDescriptions = scenario.failureDescriptions || {};
    model.currentScenario.connectors = [];
  } else {
    model.currentScenario.nodes = [
      ...model.currentScenario.nodes,
      ...processNodes(scenario.nodes)
    ];
    model.currentScenario.failureDescriptions = {
      ...model.currentScenario.failureDescriptions,
      ...scenario.failureDescriptions
    };
  }

  // To avoid problem with building scenarios endEvent can be create here and its endEventCheck are updated here.
  let endEvent = model.currentScenario.nodes.find(n => n.type === "endEvent");
  if (!endEvent) {
    const tempEndEvent = [{
      type: "endEvent",
      name: "End",
      nodeId: "node_end",
      functions: []
    }];
    const [processedEndEvent] = processNodes(tempEndEvent);
    model.currentScenario.nodes.push(processedEndEvent);
    endEvent = processedEndEvent;
  }
  endEvent.functions = [
    ...(endEvent.functions || []),
    ...(scenario.endEventChecks || [])
    ];
}


// Is called by loadScenarioData()
// Scales pools and lanes to canvas size
function loadStaticElements(elements) {
  return elements.map(element => ({
    ...element,
    coordinates: {
      x: scaleCoordinate(element.coordinates.x, 'x'),
      y: scaleCoordinate(element.coordinates.y, 'y')
    },
    size: {
      width: scaleCoordinate(element.size.width, 'width'),
      height: scaleCoordinate(element.size.height, 'height')
    }
  }));
}


// Is called by loadScenarioData()
// Gives nodes size, scaled coordinates and potentially puts them in the menu
// Shrinks or enlarges the menu to accomodate the amount of nodes
function processNodes(scenarioNodes) {
  const processed = [];

  // Defines menu grid layout constants
  const CELL_WIDTH = 140;
  const CELL_HEIGHT = 100;
  const START_X = 50;
  const BASE_HEIGHT = model.canvasProperties.height;
  const MENU_START_Y = BASE_HEIGHT;
  const CELLS_PER_ROW = Math.floor((canvas.width - START_X) / CELL_WIDTH);
  let cellIndex = 0;
  let maxRow = 0;

  // Rebuilds menuCells based on current node positions in menu area
  model.menuRef.menuCells = [];
  for (const node of model.currentScenario.nodes || []) {
    if (node.coordinates?.y >= MENU_START_Y - 10) {
      const cellX = Math.floor((node.coordinates.x - START_X) / CELL_WIDTH);
      const cellY = Math.floor((node.coordinates.y - MENU_START_Y) / CELL_HEIGHT);
      const cellIndex = cellY * CELLS_PER_ROW + cellX;
      model.menuRef.menuCells[cellIndex] = true;
      maxRow = Math.max(maxRow, cellY);
    }
  }
  
  // Sets node dimensions
  for (const node of scenarioNodes) {
    const processedNode = { ...node };
    if (node.type === "activity") {
      processedNode.width = 120;
      processedNode.height = 80;
    } else {
      processedNode.width = 60;
      processedNode.height = 60;
    }
    
    // Uses uploaded coordinates or places them in the next available menu cell and gives them coordinates
    if (node.coordinates) {
      processedNode.coordinates = {
        x: scaleCoordinate(node.coordinates.x, 'x'),
        y: scaleCoordinate(node.coordinates.y, 'y')
      };
    } else {
      while (model.menuRef.menuCells[cellIndex]) cellIndex++;
      const row = Math.floor(cellIndex / CELLS_PER_ROW);
      const col = cellIndex % CELLS_PER_ROW;      
      maxRow = Math.max(maxRow, row);      
      const xOffset = (CELL_WIDTH - processedNode.width) / 2;       
      processedNode.coordinates = {
        x: START_X + (col * CELL_WIDTH) + xOffset,
        y: MENU_START_Y + (row * CELL_HEIGHT)
      };
      
      model.menuRef.menuCells[cellIndex] = true;
      cellIndex++;
    }
    
    processed.push(processedNode);
  }
  
  const menuRows = maxRow + 1;
  canvas.height = BASE_HEIGHT + (menuRows * CELL_HEIGHT);
  
  return processed;
}


// Is called by loadStaticElements() and processNodes()
// Scales coordinates to canvas size
function scaleCoordinate(coord, dimension) {
  if (dimension === 'x' || dimension === 'width') {
    return (coord / model.referanceCanvas.width) * model.canvasProperties.width;
  } else {
    return (coord / model.referanceCanvas.height) * model.canvasProperties.height;
  }
}


// Is called by initCanvas() and nextScenario()
// Deletes the whole canvas and then redraws it in hierarchical order so that elements are layered correctly
function draw() {
  context.clearRect(0, 0, canvas.width, canvas.height);
  drawPools(model.currentScenario.pools);
  drawLanes(model.currentScenario.lanes);
  drawConnectors(model.currentScenario.connectors);
  drawNodes(model.currentScenario.nodes);
  drawTemporaryArrow();
}

// Is called by initCanvas() and nextScenario()
// For scenarios that have tutorialImage it shows it and sets up a button for retrieval
function tutorialImage() {
  const scenario = model.loadedScenarioData.scenarios[model.game.currentScenario];
  const tutorialBtn = document.getElementById("showTutorial");
  
  if (scenario.tutorialImage) {
    tutorialBtn.style.display = "inline-block";
    tutorialBtn.onclick = () => showTutorialOverlay(scenario.tutorialImage);
    showTutorialOverlay(scenario.tutorialImage);
  } else {
    tutorialBtn.style.display = "none";
  }
}

// Is called by tutorialImage()
// Shows the tutorial image and sets up so it can be clsoed again
function showTutorialOverlay(imagePath) {
  const overlay = document.getElementById("tutorialOverlay");
  const img = document.getElementById("tutorialImg");
  
  img.src = imagePath;
  overlay.style.display = "flex";
  
  document.getElementById("closeTutorial").onclick = () => {
    overlay.style.display = "none";
  };
}

// Is called by clickign Next Scenario button
// Starts transition to either next scenario or End Screen
function nextScenario() {
  verifySolution();
  document.getElementById("taskVerificationText").innerText = "Task results will appear here.";
  if (model.game.currentScenario < model.game.numberOfScenarios - 1) {
    model.game.currentScenario += 1;
    loadScenarioInformation();
    loadScenarioData();
    draw();
    tutorialImage();
  } else {
    endScreen();
  }
}


// Is called by nextScenario()
// Triggers transition to End Screen
function endScreen(){
  document.getElementById("app").style.display = "none";
  document.getElementById("end").style.display = "block";
  updateEndScreen();
}